name: CI with AI Test Analyzer

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Capture Output
        run: |
          set -o pipefail
          npm test 2>&1 | tee test-output.log
        continue-on-error: true

      - name: Analyze Failed Tests with OpenAI
        if: failure()
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Sending logs to OpenAI..."
          tail -n 50 test-output.log > logs.txt
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {"role": "system", "content": "You are a helpful assistant that explains test failures."},
                {"role": "user", "content": "'"$(cat logs.txt | jq -Rs .)"'"}
              ]
            }' | jq -r '.choices[0].message.content')
          echo "::notice::OpenAI Insight: $RESPONSE"
